

INSERT INTO 'rules' ('id', 'label', 'attribute', 'regexp',rule_type) VALUES
(3, 'Date moins 1500', 'date', 'lessthan 1500','number'),
(9, 'Entre 1500 et 1650', 'date', 'between 1500 1650','number'),
(10, 'Entre 1650 et 1750', 'date', 'between 1650 1750','number'),
(11, 'Supérieur à 1750', 'date', 'morethan 1750','number'),
(12, 'Ecole française', 'school', '(French)','text'),
(13, 'Ecole Allemande', 'school', '(German)','text'),
(14, 'Ecole italienne', 'school', '(Italian)','text'),
(16, 'ID + de 500', 'id', 'morethan 500','number'),
(17, 'Id - de 500', 'id', 'lessthan 500','number'),
(19, 'Oil', 'technique', '(Oil)','text'),
(20, 'Sand', 'technique', '(Sand)','text'),
(21, 'Wood', 'technique', '(Wood)','text'),
(23, 'Marble', 'technique', '(Marble)','text'),
(24, 'Photo', 'technique', '(Photo)','text'),
(25, 'Polychrome', 'technique', '(Poly)','text'),
(26, 'Commence par ABC', 'artist', '^(\\[ABC\\])','text'),
(27, 'Commence par DE', 'artist', '^(\\[DE\\])','text'),
(28, 'Commence FGH', 'artist', '^(\\[FGH\\])','text'),
(29, 'Commence par IJ', 'artist', '^(\\[IJ\\])','text'),
(30, 'Commence par KLM', 'artist', '^(\\[KLM\\])','text'),
(31, 'Commence par NO', 'artist', '^(\\[NO\\])','text'),
(32, 'Commence par PQR', 'artist', '^(\\[PQR\\])','text'),
(33, 'Commence par STU', 'artist', '^(\\[STU\\])','text'),
(34, 'Commence VW', 'artist', '^(\\[VW\\])','text'),
(35, 'Commence XYZ', 'artist', '^(\\[XYZ\\])','text');
